---
all_packages:
  developer:
    description: developer utilities for the Neurospaces project.
    order: 0
    tags:
      - genesis3
      - neurospaces
    version_control:
      branch_name: 0
      port_number: 4696
    version_script: neurospaces_build --version
  chemesis3:
    dependencies:
      experiment: for running the tests
    description: a simple reaction-diffusion solver
    operations:
      ./configure:
        debug:
          - CFLAGS=-g -O0
        release:
          - CFLAGS=-g -O9
    order: 2.5
    tags:
      - genesis3
    version_control:
      branch_name: 0
      port_number: 4706
  dash:
    description: a single neuron solver that uses dual exponential equations to model channel currents
    disabled: has never been integrated
    order: 2
    tags:
      - genesis3
    version_script: 0
  exchange:
    dependencies:
      model-container: for storing the model in computer memory
    description: model exchange using common standars such as NeuroML and NineML
    order: 6.5
    tags:
      - genesis3
    version_control:
      branch_name: 0
      port_number: 4701
    version_script: neurospaces_exchange --version
  experiment:
    description: Experimental protocols
    operations:
      ./configure:
        debug:
          - CFLAGS=-g -O0
        release:
          - CFLAGS=-g -O9
    order: 1.5
    tags:
      - genesis3
    version_control:
      branch_name: 0
      port_number: 4703
  g-tube:
    description: GENESIS GUI
    disabled: seems not to work properly
    order: 30
    tags:
      - genesis3
    version_control:
      branch_name: 0
      repository: /home/hugo/neurospaces_project/g-tube/source/snapshots/0/.hg
    version_script: 0
  geometry:
    description: a collection of algorithms of computational geometry useful for the conversion of EM image stacks ao.
    disabled: far from finished
    order: 4
    tags:
      - genesis3
    version_script: 0
  gshell:
    dependencies:
      heccer: for solving single neurons
      model-container: for storing the model in computer memory
      ssp: to schedule the solvers
    description: an interactive GENESIS shell environment developed in perl
    order: 13
    tags:
      - genesis3
    version_control:
      branch_name: 0
      port_number: 4699
    version_script: genesis-g3 --version
  heccer:
    dependencies:
      model-container: for storing the model in computer memory
    description: a single neuron solver
    operations:
      ./configure:
        debug:
          - CFLAGS=-g -O0
        release:
          - CFLAGS=-g -O9
    order: 2
    tags:
      - genesis3
    version_control:
      branch_name: 0
      port_number: 4694
  model-container:
    description: solver-independent model storage
    operations:
      ./configure:
        debug:
          - CFLAGS=-g -O0
        release:
          - CFLAGS=-g -O9
    order: 1
    tags:
      - genesis3
      - neurospaces
    version_control:
      branch_name: 0
      port_number: 4693
  neurospaces_prcs:
    description: 'solver-independent model storage -- OLD'
    disabled: obsoleted by the model-container under mtn control rather than prcs
    order: 0.5
    tags:
      - neurospaces
    version_control:
      commands:
        status:
          - prcs
          - diff
          - neurospaces.prj
          - '`prcs 2>/dev/null execute --not ".*\(directory\|symlink\)" neurospaces.prj | grep -v "neurospaces\.prj" | grep -v "purkinjespine" `'
          - --
          - --unified
    version_script: prcsentry Project-Version
  ns-sli:
    dependencies:
      heccer: for solving single neurons
      model-container: for storing the model in computer memory
    description: GENESIS-2 Backward Compatibility
    operations:
      ./configure:
        debug:
          - CFLAGS=-g -O0
        release:
          - CFLAGS=-g -O9
    order: 6
    tags:
      - genesis3
    version_control:
      branch_name: 0
      port_number: 4692
    version_script: 0
  project-browser:
    dependencies:
      heccer: for solving single neurons
      model-container: for storing the model in computer memory
      ssp: to schedule the solvers
    description: inspect and compare simulation output
    disabled: parts working, only for experts who are familiar with the Sesa internals
    order: 7
    tags:
      - neurospaces
    version_control:
      branch_name: 0
      port_number: 4697
    version_script: pb-version
  publications:
    description: prototyping the publication framework
    disabled: Allan's experiment working area
    order: 32
    tags:
      - genesis3
    version_control:
      branch_name: 0
      port_number: 4702
    version_script: 0
  rtxi:
    description: interface with the RTXI dynamic clamp software
    disabled: 'slow progress, yet important'
    order: 29
    tags:
      - genesis3
    version_control:
      branch_name: 0
      port_number: 4704
    version_script: 0
  ssp:
    dependencies:
      heccer: for solving single neurons
      model-container: for storing the model in computer memory
    description: simple scheduler in perl
    order: 3
    tags:
      - genesis3
    version_control:
      branch_name: 0
      port_number: 4695
  sspy:
    dependencies:
      heccer: for solving single neurons
      model-container: for storing the model in computer memory
    description: simple scheduler in python
    order: 3.1
    tags:
      - genesis3
    version_control:
      branch_name: 0
      port_number: 4705
  studio:
    dependencies:
      heccer: for solving single neurons
      model-container: for storing the model in computer memory
      ssp: to schedule the solvers
    description: visualizes and explores models in the model-container
    order: 5
    tags:
      - neurospaces
    version_control:
      branch_name: 0
      port_number: 4698
    version_script: neurospaces --version
  system:
    description: system data
    disabled: not sure anymore what this package was supposed to be doing, something with putting global data in the top-level neurospaces_project directory.
    order: 129
    tags:
      - neurospaces
    version_script: 0
  userdocs:
    description: 'all you need to know about installing, using and simulating using GENESIS 3. '
    order: 31
    tags:
      - genesis3
    version_control:
      branch_name: 0
      port_number: 4700
    version_script: 0
